"""Readable managerial Project Monitor page."""
from __future__ import annotations

import developaid_monitor_manager as _manager
_manager.install()
import developaid_monitor_dashboard as _dashboard
_dashboard.install()
import developaid_monitor_readable as _readable
_readable.install()

MONITOR_PAGE = r"""<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DevelopAid · Project Monitor</title>
<style>
:root{--bg:#f5f6f8;--card:#fff;--text:#17202b;--muted:#667085;--line:#e4e7ec;--navy:#183153;--navy2:#315474;--plan:#c9cfd7;--risk:#b42318;--riskbg:#fff1f0;--ok:#247044;--okbg:#eef8f1;--warn:#9a6700;--warnbg:#fff7df;--grid:#eef1f4}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:13px Inter,Arial,sans-serif}.wrap{max-width:1680px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:10px}h1{margin:0;font-size:24px}h2{margin:0;font-size:14px}.muted{color:var(--muted)}
.controls,.files,.auth-actions,.legend{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.field{display:flex;flex-direction:column;gap:4px}.field label{font-size:9px;text-transform:uppercase;font-weight:800;color:var(--muted)}input{height:34px;border:1px solid #d0d5dd;border-radius:6px;padding:0 8px;background:#fff}.btn{height:34px;border:0;border-radius:6px;padding:0 12px;background:var(--navy);color:#fff;font-weight:700;cursor:pointer}.btn.alt{background:#475467}.btn.ghost{background:#fff;color:var(--navy);border:1px solid #cfd5dd}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;margin-top:10px;overflow:hidden}.head{padding:12px 14px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:12px;align-items:center}.body{padding:13px 14px}.setup{display:grid;grid-template-columns:1.15fr 1fr;gap:10px}.box{border:1px solid var(--line);border-radius:8px;padding:12px;background:#fbfcfd}.box b{display:block;margin-bottom:6px}.box p{font-size:11px;line-height:1.45;color:var(--muted);margin:4px 0 10px}.msg{font-size:11px;margin-top:7px;min-height:14px}.good{color:var(--ok)}.bad{color:var(--risk)}.warn{color:var(--warn)}.hidden{display:none!important}
.kpis{display:grid;grid-template-columns:repeat(7,1fr);gap:8px}.kpi{border:1px solid var(--line);border-radius:8px;padding:11px;min-height:102px}.kpi .l{font-size:9px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);font-weight:800}.kpi .n{font-size:21px;font-weight:760;margin:8px 0 4px}.kpi .s{font-size:10px;line-height:1.35;color:var(--muted)}
.legend{font-size:10px;color:var(--muted);margin-top:5px}.lg{display:inline-flex;align-items:center;gap:5px}.sw{display:inline-block;width:20px;height:7px;border-radius:3px}.sw.plan{background:var(--plan)}.sw.fact{background:var(--navy)}.sw.late{height:3px;background:var(--risk)}.sw.ahead{height:3px;background:var(--ok)}.dot{width:7px;height:7px;border-radius:50%;background:var(--navy2);display:inline-block}.dot.planpay{background:#fff;border:1px solid #98a2b3}
.g-axis,.g-row{display:grid;grid-template-columns:360px minmax(580px,1fr) 300px}.g-axis{padding:9px 12px;border-bottom:1px solid var(--line);font-size:10px;color:var(--muted)}.axis{height:20px;position:relative}.tick{position:absolute;transform:translateX(-50%);white-space:nowrap}.g-row{min-height:58px;border-bottom:1px solid var(--grid)}.g-label,.g-metrics{padding:8px 11px}.g-label{cursor:pointer}.title{font-weight:700}.sub{font-size:10px;color:var(--muted);margin-top:4px}.chev{display:inline-block;width:16px;color:#667085}.timeline{position:relative;min-height:58px;background:repeating-linear-gradient(to right,transparent,transparent calc(12.5% - 1px),#f2f4f7 calc(12.5% - 1px),#f2f4f7 12.5%)}.cut{position:absolute;top:0;bottom:0;width:1px;background:#344054;z-index:5}.cut-label{position:absolute;top:1px;transform:translateX(4px);font-size:8px;color:#344054;white-space:nowrap;z-index:6}.planbar{position:absolute;top:19px;height:8px;background:var(--plan);border-radius:4px}.factbar{position:absolute;top:19px;height:8px;background:var(--navy);border-radius:4px;z-index:2}.latebar{position:absolute;top:31px;height:3px;background:var(--risk)}.aheadbar{position:absolute;top:31px;height:3px;background:var(--ok)}.forecast-mark{position:absolute;top:12px;width:3px;height:24px;transform:translateX(-1px);z-index:4}.forecast-mark.late{background:var(--risk)}.forecast-mark.ahead{background:var(--ok)}.forecast-mark.ontime{background:var(--navy)}.paydot{position:absolute;top:44px;width:8px;height:8px;border-radius:50%;transform:translateX(-4px);z-index:4}.paydot.fact{background:var(--navy2)}.paydot.plan{background:#fff;border:1px solid #98a2b3}.g-metrics{font-size:10px;color:var(--muted);line-height:1.35}.m-main{font-size:12px;font-weight:800;margin-bottom:3px}.status-late{color:var(--risk)}.status-ahead{color:var(--ok)}.status-ontime{color:var(--navy)}.status-future{color:var(--muted)}
.lvl-corpus{background:#f8fafc}.lvl-corpus .title{font-size:13px}.lvl-detail .g-label{padding-left:28px}.lvl-rss .g-label{padding-left:46px}.lvl-task .g-label{padding-left:64px;background:#fcfcfd}.selected{outline:2px solid #d6e0ea;outline-offset:-2px}
.finbox{margin-top:6px}.finline{display:flex;justify-content:space-between;gap:8px;font-size:9px}.fundbar{height:8px;border-radius:4px;background:#eaecf0;position:relative;margin-top:3px;overflow:visible}.fundpaid{position:absolute;left:0;top:0;bottom:0;background:var(--navy2);border-radius:4px}.needmark{position:absolute;top:-3px;height:14px;width:2px;background:var(--warn)}.overflow{margin-top:3px;font-size:9px;color:var(--risk);font-weight:700}.scope{font-size:8px;color:var(--muted);margin-top:2px}
.detail-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.mini{border:1px solid var(--line);border-radius:7px;padding:10px}.mini .l{font-size:9px;text-transform:uppercase;color:var(--muted);font-weight:800}.mini .v{font-size:17px;font-weight:750;margin-top:5px}.links{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.links>div{border-top:1px solid var(--line);padding-top:8px}.linkrow{font-size:11px;margin:5px 0;line-height:1.35}
@media(max-width:1200px){.kpis{grid-template-columns:repeat(3,1fr)}.setup{grid-template-columns:1fr}.g-axis,.g-row{grid-template-columns:280px minmax(500px,1fr) 250px}.wrap{overflow-x:auto}}
</style>
</head>
<body><div class="wrap">
<div class="top"><div><h1>DevelopAid · Project Monitor</h1><div class="muted">Общий Dashboard проекта → корпуса → этапы → RSS/WBS. План, КС-факт, forecast и деньги читаются раздельно.</div></div><div class="controls"><div class="field"><label>Проект</label><input id="project" value="Кутузов Сити"></div><div class="field"><label>Срез</label><input id="cut" type="date"></div><button class="btn" id="refresh">Обновить</button></div></div>
<div class="card" id="loginBox"><div class="body"><b>Вход в Project Monitor</b><div class="auth-actions" style="margin-top:8px"><button class="btn" id="loginBtn">Войти через Telegram</button><button class="btn ghost" id="keyBtn">Ключ администратора</button><button class="btn ghost hidden" id="logoutBtn">Выйти</button><span id="loginState"></span></div><div class="msg" id="loginMsg"></div></div></div>
<div id="privateArea" class="hidden">
<div class="card"><div class="head"><h2>Инициализация и обновление</h2><span class="muted">benchmark фиксируется один раз</span></div><div class="body setup">
<div class="box"><b>1 · Benchmark проекта</b><p>ГПР/WBS + финансовая книга + сырой PM. Повторно загружать benchmark при обычном еженедельном обновлении не нужно.</p><div class="files"><input id="gpr" type="file" accept=".xlsx"><span class="muted">ГПР+RSS</span><input id="finance" type="file" accept=".xlsx"><span class="muted">ФМ</span><input id="pm" type="file" accept=".xlsx"><span class="muted">сырой PM</span><input id="baselineDate" type="date"><button class="btn alt" id="baselineBtn">Зафиксировать</button></div><div class="msg" id="baselineMsg"></div><div style="margin-top:10px;border-top:1px solid var(--line);padding-top:9px"><b>Утверждённый rebaseline</b><div class="files"><input id="rebase" type="file" accept=".xlsx"><input id="rebaseCode" value="2.2.2.6"><input id="rebaseSheet" value="наше предложение"><button class="btn alt" id="rebaseBtn">Добавить</button></div><div class="msg" id="rebaseMsg"></div></div></div>
<div class="box"><b>2 · Еженедельный срез</b><p>Состояние работ берётся из актов РСС. Forecast строится из КС-процента относительно планового процента на дату среза; положительные задержки проходят через зависимости PM.</p><div class="files"><input id="rss" type="file" accept=".xlsx"><input id="rssDate" type="date"><button class="btn alt" id="rssBtn">Загрузить РСС</button></div><div class="files" style="margin-top:8px"><input id="sales" type="file" accept=".xlsx"><button class="btn alt" id="salesBtn">Загрузить продажи</button></div><div class="msg" id="weeklyMsg"></div></div>
</div></div>
<div class="card hidden" id="dashCard"><div class="head"><h2>Общий Dashboard проекта</h2><span class="muted" id="source"></span></div><div class="body"><div class="kpis" id="kpis"></div></div></div>
<div class="card hidden" id="ganttCard"><div class="head"><div><h2>Управленческий Гант</h2><div class="legend"><span class="lg"><i class="sw plan"></i>утверждённый план</span><span class="lg"><i class="sw fact"></i>КС-факт / эквивалент выполнения</span><span class="lg"><i class="sw late"></i>просрочка forecast</span><span class="lg"><i class="sw ahead"></i>опережение</span><span class="lg"><i class="dot"></i>факт оплаты</span><span class="lg"><i class="dot planpay"></i>план оплаты</span></div></div><span class="muted">корпуса идут отдельными блоками; клик раскрывает детализацию</span></div><div id="gantt"></div></div>
<div class="card hidden" id="detailCard"><div class="head"><h2 id="detailTitle">Детали</h2><span class="muted">сроки · КС · лимит · потребность · зависимости</span></div><div class="body"><div class="detail-grid" id="detailGrid"></div><div class="links"><div><b>Предшественники</b><div id="pred"></div></div><div><b>Последователи</b><div id="succ"></div></div></div></div></div>
</div><div class="msg bad" id="viewMsg"></div></div>
<script>
'use strict';
const $=id=>document.getElementById(id), expanded=new Set(), WEB_SESSION_KEY='developaid_web_session', ADMIN_KEY='plato_projects_key';let selected=null, seededExpand=false;
const today=new Date().toISOString().slice(0,10);$('cut').value=today;$('rssDate').value=today;$('baselineDate').value=today;
function readStorage(...keys){try{for(const k of keys){const v=localStorage.getItem(k);if(v)return v}}catch(e){}return ''}function session(){return readStorage(WEB_SESSION_KEY,'session','developaid_session')}function adminKey(){return readStorage(ADMIN_KEY,'key','developaid_key')}function hasAuth(){return !!(session()||adminKey())}function auth(){return {session:session(),key:adminKey()}}function msg(id,t,cls=''){const e=$(id);if(!e)return;e.textContent=t;e.className='msg '+cls}function syncAuthUi(){const yes=hasAuth();$('loginBox').classList.toggle('hidden',yes);$('privateArea').classList.toggle('hidden',!yes);$('logoutBtn').classList.toggle('hidden',!yes);$('loginState').textContent=yes?'Вход выполнен':'';return yes}function requireLogin(t='Войдите через Telegram.'){$('loginBox').classList.remove('hidden');$('privateArea').classList.add('hidden');msg('loginMsg',t,'bad')}
async function post(path,p){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.assign(auth(),p||{}))}),d=await r.json().catch(()=>({}));if(r.status===401)requireLogin();if(!r.ok)throw new Error(d.detail||('HTTP '+r.status));return d}const b64=f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});
function money(v){if(v==null||!isFinite(Number(v)))return '—';const n=Number(v);return Math.abs(n)>=1e9?(n/1e9).toLocaleString('ru-RU',{maximumFractionDigits:2})+' млрд ₽':(n/1e6).toLocaleString('ru-RU',{maximumFractionDigits:1})+' млн ₽'}function pct(v){return v==null||!isFinite(Number(v))?'—':(Number(v)*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%'}function dt(v){if(!v)return '—';const d=new Date(v+'T00:00:00');return isNaN(d)?v:d.toLocaleDateString('ru-RU')}function kpi(l,n,s='',cls=''){return `<div class="kpi"><div class="l">${l}</div><div class="n ${cls}">${n}</div><div class="s">${s}</div></div>`}
$('loginBtn').onclick=async()=>{msg('loginMsg','Открываю Telegram…','good');try{const r=await fetch('/auth/telegram/start',{method:'POST'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Вход недоступен');if(d.link)window.open(d.link,'_blank');for(let i=0;i<60;i++){await new Promise(ok=>setTimeout(ok,2000));const c=await fetch('/auth/telegram/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:d.code})}),cd=await c.json().catch(()=>({}));if(c.ok&&cd.session){localStorage.setItem(WEB_SESSION_KEY,cd.session);syncAuthUi();await refresh();return}}throw new Error('Подтверждение не пришло')}catch(e){msg('loginMsg',e.message,'bad')}};$('keyBtn').onclick=()=>{const k=prompt('Ключ администратора');if(k){localStorage.setItem(ADMIN_KEY,k.trim());syncAuthUi();refresh()}};$('logoutBtn').onclick=()=>{[WEB_SESSION_KEY,'session','developaid_session',ADMIN_KEY,'key','developaid_key'].forEach(k=>localStorage.removeItem(k));syncAuthUi();requireLogin('Сессия удалена.')};
$('baselineBtn').onclick=async()=>{const g=$('gpr').files[0],f=$('finance').files[0],pm=$('pm').files[0],d=$('baselineDate').value,p=$('project').value.trim();if(!g||!f)return msg('baselineMsg','Нужны ГПР+RSS и финансовая книга','bad');try{msg('baselineMsg','Фиксирую benchmark…','good');await post('/monitor/schedule',{project:p,taken_at:d,gpr_base64:await b64(g),pm_base64:await b64(f)});if(pm)await post('/monitor/proposal',{project:p,taken_at:d,start:d,code:'__PM__',sheet:'Таблица_задач1',content_base64:await b64(pm)});msg('baselineMsg','Benchmark создан.','good');await refresh()}catch(e){msg('baselineMsg',e.message,'bad')}};$('rebaseBtn').onclick=async()=>{const f=$('rebase').files[0];if(!f)return msg('rebaseMsg','Выберите файл rebaseline','bad');try{await post('/monitor/proposal',{project:$('project').value.trim(),taken_at:$('cut').value,start:$('cut').value,code:$('rebaseCode').value.trim(),sheet:$('rebaseSheet').value.trim(),content_base64:await b64(f)});msg('rebaseMsg','Rebaseline сохранён.','good');await refresh()}catch(e){msg('rebaseMsg',e.message,'bad')}};$('rssBtn').onclick=async()=>{const f=$('rss').files[0],d=$('rssDate').value;if(!f)return msg('weeklyMsg','Выберите РСС 6.1.2','bad');try{await post('/monitor/estimate',{project:$('project').value.trim(),taken_at:d,filename:f.name,content_base64:await b64(f)});$('cut').value=d;msg('weeklyMsg','РСС загружен.','good');await refresh()}catch(e){if(String(e.message).includes('уже загружен')){$('cut').value=d;msg('weeklyMsg','Этот срез уже сохранён — открываю его.','warn');await refresh();return}msg('weeklyMsg',e.message,'bad')}};$('salesBtn').onclick=async()=>{const f=$('sales').files[0];if(!f)return msg('weeklyMsg','Выберите отчёт продаж','bad');try{await post('/monitor/sales',{project:$('project').value.trim(),taken_at:$('cut').value,content_base64:await b64(f)});msg('weeklyMsg','Продажи сохранены.','good');await refresh()}catch(e){msg('weeklyMsg',e.message,'bad')}};
function renderDash(v){const d=v.dashboard||{},s=d.schedule||{},ph=d.physical||{},f=d.funding||{},approved=s.approved_finish,forecast=s.forecast_finish,delay=s.rnv_delay_days;let forecastText=s.forecast_known?dt(forecast):'—',forecastSub=s.forecast_known?(delay>0?`отставание +${delay} дн`:delay<0?`опережение ${delay} дн`:'без сдвига'):'нет расчётного отклонения';$('dashCard').classList.remove('hidden');$('source').textContent=(d.sources&&d.sources.rss)||'';$('kpis').innerHTML=kpi('Утверждённый РНВ',dt(approved),'baseline PM')+kpi('Current Forecast РНВ',forecastText,forecastSub,delay>0?'bad':delay<0?'good':'')+kpi('КС / утв. модель',pct(ph.completion),`${money(ph.accepted)} актировано`)+kpi('Остаток потребности',money(f.remaining_need),`до ${dt(f.forecast_to)}`)+kpi('Резерв',money(f.reserve),`использование с ${dt(f.reserve_start)}`,'warn')+kpi('Исчерпание резерва',dt(f.reserve_exhaustion),`остаток ${money(f.reserve_balance)}`,f.reserve_exhaustion?'bad':'')+kpi('Доп. финансирование',money(f.additional_financing),f.known?'после лимитов статей и резерва':(f.reason||'нет данных'),f.additional_financing>0?'bad':'good')}
function collect(nodes,out=[]){for(const n of nodes||[]){out.push(n);collect(n.children||[],out)}return out}function toDate(v){if(!v)return null;const d=new Date(v+'T00:00:00');return isNaN(d)?null:d}function statusClass(delta,status){if(status==='БУДУЩАЯ ЗАДАЧА')return 'status-future';if(delta>3)return 'status-late';if(delta<-3)return 'status-ahead';return 'status-ontime'}function statusText(n){const d=n.delta_days==null?null:Number(n.delta_days);if(n.status==='ЗАВЕРШЕНО')return 'ЗАВЕРШЕНО';if(n.status==='БУДУЩАЯ ЗАДАЧА')return 'БУДУЩАЯ';if(d==null)return n.status||'НЕТ ДАННЫХ';if(d>3)return `ОТСТАВАНИЕ +${d} дн`;if(d<-3)return `ОПЕРЕЖЕНИЕ ${d} дн`;return 'В СРОК'}
function renderFinance(n){const f=n.finance||{};if(n.level!=='rss'||!f.limit)return '';const paid=Math.max(0,Math.min(100,(Number(f.paid_ratio)||0)*100)),need=(Number(f.need_ratio)||0)*100,mark=Math.max(0,Math.min(100,need)),overflow=Number(f.overflow)||0;return `<div class="finbox" title="Лимит: ${money(f.limit)} · оплачено: ${money(f.paid)} · потребность по модели от среза: ${money(f.need)}"><div class="finline"><span>оплачено ${pct(f.paid_ratio)}</span><span>потребность / лимит ${pct(f.need_ratio)}</span></div><div class="fundbar"><span class="fundpaid" style="width:${paid}%"></span><span class="needmark" style="left:${mark}%"></span></div>${overflow>0?`<div class="overflow">не покрыто собственным лимитом: ${money(overflow)}</div>`:''}<div class="scope">${f.scope||''}${f.first_reserve_month?` · резерв с ${dt(f.first_reserve_month)}`:''}</div></div>`}
function renderGantt(v){const roots=(v.schedule&&v.schedule.management)||[];if(!roots.length){$('ganttCard').classList.add('hidden');return}$('ganttCard').classList.remove('hidden');if(!seededExpand){for(const n of collect(roots,[])){if(n.level==='control'||n.level==='corpus')expanded.add(n.key)}seededExpand=true}const all=collect(roots,[]),dates=[];for(const n of all){['plan_start','plan_finish','forecast_finish','actual_equivalent_date'].forEach(k=>{const d=toDate(n[k]);if(d)dates.push(d)})}if(!dates.length)return;let min=new Date(Math.min(...dates.map(d=>+d))),max=new Date(Math.max(...dates.map(d=>+d)));min.setDate(min.getDate()-15);max.setDate(max.getDate()+20);const span=Math.max(1,+max-+min),pos=x=>{const d=toDate(x);return d?Math.max(0,Math.min(100,(+d-+min)/span*100)):null};let html='<div class="g-axis"><div>Корпус / этап / RSS / WBS</div><div class="axis">';for(let i=0;i<=7;i++){const d=new Date(+min+span*i/7);html+=`<span class="tick" style="left:${i/7*100}%">${d.toLocaleDateString('ru-RU',{month:'short',year:'2-digit'})}</span>`}html+='</div><div>Статус · деньги</div></div>';const cp=pos(v.cut);
function row(n){const key=n.key||('task:'+String(n.id||n.wbs||n.name)),kids=(n.children||[]).filter(Boolean),open=expanded.has(key),lvl=n.level||'task',ps=pos(n.plan_start),pf=pos(n.plan_finish),ae=pos(n.actual_equivalent_date),ff=pos(n.forecast_finish),delta=n.delta_days==null?null:Number(n.delta_days),pay=n.payments||{},sel=selected===key?' selected':'';let t='';if(cp!=null)t+=`<span class="cut" style="left:${cp}%"></span><span class="cut-label" style="left:${cp}%">срез</span>`;if(ps!=null&&pf!=null)t+=`<span class="planbar" style="left:${ps}%;width:${Math.max(.5,pf-ps)}%" title="План ${dt(n.plan_start)} → ${dt(n.plan_finish)}"></span>`;if(ps!=null&&ae!=null)t+=`<span class="factbar" style="left:${ps}%;width:${Math.max(0,ae-ps)}%" title="КС-факт ${pct(n.actual_progress)} · эквивалент даты ${dt(n.actual_equivalent_date)}"></span>`;if(ff!=null&&pf!=null){if(delta>3)t+=`<span class="latebar" style="left:${pf}%;width:${Math.max(0,ff-pf)}%"></span>`;if(delta<-3)t+=`<span class="aheadbar" style="left:${ff}%;width:${Math.max(0,pf-ff)}%"></span>`;t+=`<span class="forecast-mark ${delta>3?'late':delta<-3?'ahead':'ontime'}" style="left:${ff}%" title="Forecast ${dt(n.forecast_finish)} · ${statusText(n)}"></span>`}if(lvl==='rss'){for(const [m,a] of Object.entries(pay.plan||{})){const x=pos(m);if(x!=null)t+=`<span class="paydot plan" style="left:${x}%" title="${dt(m)} · план оплаты ${money(a)}"></span>`}for(const [m,a] of Object.entries(pay.fact||{})){const x=pos(m);if(x!=null)t+=`<span class="paydot fact" style="left:${x}%" title="${dt(m)} · факт оплаты ${money(a)}"></span>`}}const prog=(n.actual_progress==null?'':`КС ${pct(n.actual_progress)} · план ${pct(n.plan_progress)}`),datesText=`план ${dt(n.plan_finish)}${n.forecast_finish?` · forecast ${dt(n.forecast_finish)}`:''}`;html+=`<div class="g-row lvl-${lvl}${sel}" data-key="${key}"><div class="g-label"><span class="chev">${kids.length?(open?'▾':'▸'):''}</span><span class="title">${n.code?`${n.code} · `:''}${n.name||n.wbs||''}</span><div class="sub">${lvl==='corpus'?'отдельный корпус':lvl==='rss'?'RSS · финансовая статья':lvl==='task'?'WBS '+(n.wbs||n.id||''):lvl==='detail'?'этап':'управленческий блок'}</div></div><div class="timeline">${t}</div><div class="g-metrics"><div class="m-main ${statusClass(delta,n.status)}">${statusText(n)}</div><div>${prog}</div><div>${datesText}</div>${renderFinance(n)}</div></div>`;if(open)for(const c of kids)row(c)}for(const r of roots)row(r);$('gantt').innerHTML=html;document.querySelectorAll('.g-row').forEach(el=>el.onclick=()=>{const n=collect(roots,[]).find(x=>(x.key||('task:'+String(x.id||x.wbs||x.name)))===el.dataset.key);if(!n)return;selected=el.dataset.key;if((n.children||[]).length){expanded.has(el.dataset.key)?expanded.delete(el.dataset.key):expanded.add(el.dataset.key)}renderGantt(v);renderDetail(n)})}
function renderDetail(n){$('detailCard').classList.remove('hidden');$('detailTitle').textContent=(n.code?`${n.code} · `:'')+(n.name||n.wbs||'Детали');const dep=n.dependencies||{},f=n.finance||{},d=n.delta_days==null?null:Number(n.delta_days);$('detailGrid').innerHTML=`<div class="mini"><div class="l">Статус</div><div class="v ${statusClass(d,n.status)}">${statusText(n)}</div><div class="sub">план ${dt(n.plan_finish)} · forecast ${dt(n.forecast_finish)}</div></div><div class="mini"><div class="l">КС / план</div><div class="v">${pct(n.actual_progress)}</div><div class="sub">плановый % на срез ${pct(n.plan_progress)}</div></div><div class="mini"><div class="l">Оплачено</div><div class="v">${money(f.paid||(n.payments||{}).fact_total)}</div><div class="sub">лимит ${money(f.limit)}</div></div><div class="mini"><div class="l">Потребность</div><div class="v">${money(f.need)}</div><div class="sub">остаток лимита ${money(f.remaining_limit)}</div></div><div class="mini"><div class="l">Float</div><div class="v">${dep.current_float_days==null?'—':dep.current_float_days+' дн'}</div><div class="sub">влияние на РНВ ${dep.impact_rnv_days||0} дн</div></div>`;const fmt=x=>`<div class="linkrow"><b>${x.id}</b> ${x.name||''}<br><span class="muted">${x.type||''}${x.lag_days?` ${x.lag_days>0?'+':''}${x.lag_days} дн`:''}</span></div>`;$('pred').innerHTML=(dep.predecessors||[]).map(fmt).join('')||'<span class="muted">—</span>';$('succ').innerHTML=(dep.successors||[]).map(fmt).join('')||'<span class="muted">—</span>'}
async function refresh(){if(!hasAuth()){syncAuthUi();msg('viewMsg','Войдите через Telegram.','bad');return}syncAuthUi();const p=$('project').value.trim();if(!p)return;try{msg('viewMsg','');const raw=await post('/monitor/view',{project:p,cut:$('cut').value,upto:''}),v=raw.snapshot||raw.view||raw.report||raw.response||raw;renderDash(v);renderGantt(v)}catch(e){msg('viewMsg',e.message,'bad')}}$('refresh').onclick=refresh;syncAuthUi();if(hasAuth())refresh();else msg('viewMsg','Войдите через Telegram, чтобы открыть данные проекта.','bad');
</script>
</body></html>"""
