"""Minimal Project Monitor UI: one fixed baseline, then weekly RSS only."""

MONITOR_PAGE = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title>DevelopAid — Project Monitor</title>
<style>
*{box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;background:#f5f6f7;color:#17191c}
header{background:#111820;color:white;padding:16px 22px;display:flex;gap:12px;align-items:baseline}header h1{font-size:18px;margin:0}.ver{font-size:11px;color:#89939e}
main{max-width:1240px;margin:auto;padding:18px}.card{background:#fff;border:1px solid #e0e4e8;border-radius:10px;padding:15px 17px;margin-bottom:14px}
h2{font-size:14px;margin:0 0 10px}.muted{font-size:12px;color:#68727d}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:9px}
.kpi{border:1px solid #e7e9ec;border-radius:8px;padding:10px}.kpi .l{font-size:11px;color:#68727d}.kpi .n{font-size:18px;font-weight:650;margin-top:2px}.bad{color:#b42318}.good{color:#067647}
input,button{font:inherit;border:1px solid #c8cdd3;border-radius:7px;padding:7px 9px;background:white}button{cursor:pointer}button.dark{background:#111820;color:white;border-color:#111820}input[type=file]{padding:5px;font-size:12px}.msg{font-size:12px;margin-top:7px;min-height:15px}.err{color:#b42318}.ok{color:#067647}
table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid #edf0f2;padding:6px 7px;text-align:right;white-space:nowrap}th{font-size:11px;color:#68727d;font-weight:550}th:first-child,td:first-child,.left{text-align:left;white-space:normal}.scroll{overflow:auto}.pill{font-size:11px;padding:2px 8px;border-radius:999px;background:#eef1f4;margin-left:5px}
.setup{border-left:3px solid #6b7785}.weekly{border-left:3px solid #111820}.section-note{margin-top:-5px;margin-bottom:10px}.status-bad{color:#b42318;font-weight:600}.status-good{color:#067647;font-weight:600}.status-muted{color:#68727d}
.barline{position:relative;height:22px;min-width:760px;border-bottom:1px solid #f0f1f3}.barname{position:absolute;left:0;width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;padding-top:3px}.track{position:absolute;left:270px;right:0;top:4px;height:13px;background:#f1f3f5;border-radius:2px}.planbar,.factbar{position:absolute;top:0;height:13px;border-radius:2px}.planbar{background:#b9c2cc}.factbar{background:#4d789f;height:7px;top:3px}
#loginBox{display:none}
</style></head><body>
<header><h1>DevelopAid · Project Monitor</h1><span class="ver">__VERSION__</span></header><main>
<div class="card" id="loginBox"><h2>Нужен вход</h2><div class="muted">Используется та же сессия, что в DevelopAid. Если она истекла, откройте основной сервис и войдите снова.</div></div>
<div class="card"><div class="row"><label>Проект <input id="project" value="Гродненская"></label><label>Срез <input id="cut" type="date"></label><button class="dark" id="refresh">Обновить</button><span class="muted" id="source"></span></div><div class="msg" id="viewMsg"></div></div>
<div class="card setup"><h2>1. Baseline проекта <span class="pill">один раз</span></h2><div class="muted section-note">Загрузите подготовленный PM/ГПР с привязкой к кодам РСС. Подходит и DevelopAid Project Control: из него берутся «BASELINE ГПР» и план оплат «CF ПЛАН-ФАКТ». После создания baseline не меняется от еженедельных загрузок.</div><div class="row"><input type="file" id="baselineFile" accept=".xlsx"><label>дата baseline <input id="baselineDate" type="date"></label><button id="baselineBtn">Создать baseline</button><span class="muted" id="baselineState"></span></div><div class="msg" id="baselineMsg"></div></div>
<div class="card weekly"><h2>2. Еженедельное обновление <span class="pill">только РСС 6.1.2</span></h2><div class="muted section-note">Один файл обновляет сразу два факта: акты — выполнение ГПР, «Реестр платежей» — оплаты. Другие файлы для недельного мониторинга не нужны.</div><div class="row"><input type="file" id="rssFile" accept=".xlsx"><label>дата среза <input id="rssDate" type="date"></label><button class="dark" id="rssBtn">Загрузить РСС и пересчитать</button><span class="muted" id="rssHistory"></span></div><div class="msg" id="rssMsg"></div></div>
<div class="card" id="summaryCard" style="display:none"><h2>Свод</h2><div class="grid" id="summary"></div></div>
<div class="card" id="ganttCard" style="display:none"><h2>ГПР · план / факт РСС / прогноз</h2><div class="muted section-note">Факт — стоимостная готовность по принятым работам РСС, привязанная к строке ГПР по RSS‑ключу. Это не подмена фактических PM‑дат.</div><div class="scroll" id="gantt"></div></div>
<div class="card" id="worksCard" style="display:none"><h2>Работы</h2><div class="scroll"><table id="works"></table></div></div>
<div class="card" id="cashCard" style="display:none"><h2>Оплаты · план / факт</h2><div class="muted section-note" id="cashNote"></div><div class="scroll"><table id="cash"></table></div></div>
<div class="card" id="trendCard" style="display:none"><h2>История недельных срезов РСС</h2><div class="scroll"><table id="trend"></table></div></div>
</main><script>
'use strict';const $=id=>document.getElementById(id),SESSION='developaid_web_session',ADMIN='plato_projects_key';const sess=()=>{try{return localStorage.getItem(SESSION)||''}catch(e){return''}},key=()=>{try{return localStorage.getItem(ADMIN)||''}catch(e){return''}};const today=()=>new Date().toISOString().slice(0,10),money=v=>v==null?'—':(Number(v)/1e6).toLocaleString('ru-RU',{maximumFractionDigits:1})+' млн ₽',pct=v=>v==null?'—':(Number(v)*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%',date=v=>v?String(v).slice(0,10):'—';$('cut').value=$('rssDate').value=$('baselineDate').value=today();
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({session:sess(),key:key()},body||{}))});const d=await r.json().catch(()=>({}));if(r.status===401)$('loginBox').style.display='';if(!r.ok)throw new Error(d.detail||('HTTP '+r.status));return d}async function get(path,p){const q=new URLSearchParams(Object.assign({session:sess(),key:key()},p||{})),r=await fetch(path+'?'+q),d=await r.json().catch(()=>({}));if(r.status===401)$('loginBox').style.display='';if(!r.ok)throw new Error(d.detail||('HTTP '+r.status));return d}const b64=f=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});function msg(id,text,good=false){const e=$(id);e.textContent=text;e.className='msg '+(good?'ok':'err')}function kpi(label,value,cls=''){return `<div class="kpi"><div class="l">${label}</div><div class="n ${cls}">${value}</div></div>`}function statusClass(s){return s==='В СРОК'||s==='ЗАВЕРШЕНО'?'status-good':(s==='ОТСТАВАНИЕ'||s==='НЕТ ТЕМПА / РИСК'?'status-bad':'status-muted')}
async function loadSnapshots(){const p=$('project').value.trim();if(!p)return;try{const s=await get('/monitor/snapshots',{project:p});$('baselineState').textContent=s.baseline&&s.baseline.length?'Baseline создан':'Baseline ещё не создан';$('rssHistory').textContent=(s.estimate||[]).length?`${s.estimate.length} срез(ов): ${(s.estimate||[]).join(', ')}`:'Срезов РСС пока нет'}catch(e){}}
$('baselineBtn').onclick=async()=>{const f=$('baselineFile').files[0],p=$('project').value.trim();if(!f)return msg('baselineMsg','Выберите baseline-файл');try{msg('baselineMsg','Загружаю…',true);const d=await post('/monitor/schedule',{project:p,taken_at:$('baselineDate').value,gpr_base64:await b64(f),pm_base64:''});msg('baselineMsg',`Baseline создан: ${d.works||'—'} работ${d.payment_plan?' · план оплат найден':' · план оплат в этом файле не найден'}`,true);await loadSnapshots();await refresh()}catch(e){msg('baselineMsg',e.message)}};
$('rssBtn').onclick=async()=>{const f=$('rssFile').files[0],p=$('project').value.trim(),d=$('rssDate').value;if(!f)return msg('rssMsg','Выберите свежую 6.1.2');try{msg('rssMsg','Читаю акты и платежи…',true);await post('/monitor/estimate',{project:p,taken_at:d,filename:f.name,content_base64:await b64(f)});$('cut').value=d;msg('rssMsg','Срез сохранён. План-факт пересчитан.',true);await loadSnapshots();await refresh()}catch(e){msg('rssMsg',e.message)}};$('refresh').onclick=()=>refresh();$('project').onchange=()=>loadSnapshots();
function renderSummary(v){const s=v.schedule||{},m=v.money||{},p=v.payments||{};$('summaryCard').style.display='';$('summary').innerHTML=kpi('Baseline конец',date(s.baseline_end))+kpi('Прогноз конца',date(s.forecast_end),s.forecast_end&&s.baseline_end&&s.forecast_end>s.baseline_end?'bad':'good')+kpi('Рисковых работ',String(s.risks||0),s.risks?'bad':'good')+kpi('Выполнено по РСС',money(m.accepted))+kpi('Оплачено по РСС',money(m.payment_fact))+kpi('План оплат',p.known?money(p.plan_total):'не загружен')}
function renderWorks(v){const rows=(v.schedule||{}).rows||[];$('worksCard').style.display='';$('works').innerHTML='<tr><th>Работа</th><th>RSS</th><th>План %</th><th>Факт %</th><th>Темп 3м/мес</th><th>Треб. темп</th><th>Прогноз</th><th>Δ дней</th><th>Статус</th></tr>'+rows.map(r=>`<tr><td class="left"><b>${r.wbs||''}</b> ${r.name||''}</td><td>${r.code||'—'}</td><td>${pct(r.plan_progress)}</td><td>${pct(r.actual_progress)}</td><td>${pct(r.rate_3m)}</td><td>${pct(r.required_rate)}</td><td>${date(r.forecast_finish)}</td><td>${r.delta_days==null?'—':r.delta_days}</td><td class="${statusClass(r.status)}">${r.status}</td></tr>`).join('')}
function renderCash(v){const p=v.payments||{},rows=p.rows||[];$('cashCard').style.display='';$('cashNote').textContent=p.known?'План — фиксированный baseline; факт — «Реестр платежей» текущего РСС.':'В baseline-файле не найден «CF ПЛАН-ФАКТ»: факт оплат показан, но план не выдумывается.';$('cash').innerHTML='<tr><th>Месяц</th><th>План</th><th>Факт</th><th>Δ</th></tr>'+rows.map(r=>`<tr><td class="left">${r.month.slice(0,7)}</td><td>${money(r.plan)}</td><td>${money(r.fact)}</td><td class="${r.delta!=null&&r.delta>0?'bad':''}">${money(r.delta)}</td></tr>`).join('')}
function renderGantt(v){const rows=(v.schedule||{}).rows||[];if(!rows.length)return;$('ganttCard').style.display='';let min=new Date(Math.min(...rows.map(r=>new Date(r.plan_start)))),max=new Date(Math.max(...rows.map(r=>new Date(r.forecast_finish||r.plan_finish))));if(!(max>min))max=new Date(min.getTime()+86400000);const span=max-min,pos=d=>Math.max(0,Math.min(100,(new Date(d)-min)/span*100));let h=`<div class="muted" style="margin:0 0 8px 270px">${date(min.toISOString())} — ${date(max.toISOString())}</div>`;for(const r of rows){const l=pos(r.plan_start),w=Math.max(.3,pos(r.plan_finish)-l),fw=r.actual_equivalent_date?Math.max(0,pos(r.actual_equivalent_date)-l):0;h+=`<div class="barline"><div class="barname ${statusClass(r.status)}">${r.wbs||''} · ${r.name||''}</div><div class="track"><i class="planbar" style="left:${l}%;width:${w}%"></i><i class="factbar" style="left:${l}%;width:${fw}%"></i></div></div>`}$('gantt').innerHTML=h}
function renderTrend(t){$('trendCard').style.display=t.length?'':'none';if(!t.length)return;$('trend').innerHTML='<tr><th>Срез</th><th>Выполнено</th><th>Оплачено</th><th>Рисков</th><th>Прогноз конца</th></tr>'+t.map(r=>`<tr><td class="left">${r.snapshot}</td><td>${money(r.accepted)}</td><td>${money(r.payment_fact||r.paid)}</td><td>${r.risks==null?'—':r.risks}</td><td>${date(r.forecast_end)}</td></tr>`).join('')}
async function refresh(){const p=$('project').value.trim(),cut=$('cut').value;if(!p||!cut)return;msg('viewMsg','');try{const d=await post('/monitor/view',{project:p,cut:cut,upto:''});const v=d.snapshot||d.view||d.report||d,t=d.trend||[];$('source').textContent=`РСС: ${(v.source||{}).estimate||'—'} · baseline фиксирован`;renderSummary(v);renderWorks(v);renderCash(v);renderGantt(v);renderTrend(t)}catch(e){['summaryCard','ganttCard','worksCard','cashCard','trendCard'].forEach(id=>$(id).style.display='none');msg('viewMsg',e.message)}}loadSnapshots().then(refresh);
</script></body></html>"""
