"""Isolated investment board for the twelve KRT auction lots."""
from __future__ import annotations

from fastapi import Query
from fastapi.responses import HTMLResponse, JSONResponse

from auction_search import krt_12_analysis


PAGE = r'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>12 КРТ · DevelopAid</title><style>
:root{--bg:#f1f1ee;--panel:#fff;--text:#171717;--muted:#707070;--line:#deded9;--soft:#f7f7f4;--dark:#111;--red:#9c2929;--amber:#8a5d11;--blue:#315d86}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
.shell{max-width:1540px;margin:auto;background:#fff;min-height:100vh}.brand{padding:18px 28px 0;font-size:23px;font-weight:800}.bar{height:7px;background:#111;margin-top:12px}
.head{padding:18px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;align-items:end}.head h1{margin:0;font-size:29px}.muted{color:var(--muted)}
.content{padding:18px 28px 44px}.tools{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.tools input,.tools select,.tools button{height:40px;border:1px solid var(--line);background:#fff;padding:0 11px;font:inherit}.tools input{min-width:270px}.tools button{border-color:#111;font-weight:650}.tools .primary{background:#111;color:#fff}
.note{border:1px solid var(--line);background:var(--soft);padding:10px 12px;margin-bottom:14px}.cards{display:grid;gap:12px}
.card{border:1px solid var(--line);background:#fff}.cardtop{display:grid;grid-template-columns:72px 230px minmax(230px,1.15fr) minmax(620px,2.6fr);min-height:190px}
.rank{display:flex;flex-direction:column;align-items:center;justify-content:center;border-right:1px solid var(--line);background:var(--soft)}.rank b{font-size:28px}.rank span{font-size:10px;color:var(--muted);text-transform:uppercase}
.map{position:relative;overflow:hidden;background:#ecece8;border-right:1px solid var(--line)}.map img,.map svg{position:absolute;inset:0;width:100%;height:100%}.map .mapmsg{position:absolute;left:8px;bottom:8px;right:8px;background:rgba(255,255,255,.9);padding:5px 7px;font-size:10px}
.identity{padding:14px;border-right:1px solid var(--line)}.lotbadge{display:inline-block;border:1px solid var(--line);padding:3px 6px;font-size:10px;margin-bottom:8px}.identity h2{font-size:17px;line-height:1.25;margin:0 0 5px}.identity .slug{font-size:11px;color:var(--muted);margin-top:8px}
.metrics{display:grid;grid-template-columns:repeat(4,1fr)}.metric{padding:12px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);min-height:82px}.metric:nth-child(4n){border-right:0}.metric:nth-last-child(-n+4){border-bottom:0}.metric b{display:block;font-size:16px}.metric small{display:block;color:var(--muted);font-size:10px;margin-top:4px}
.score100{font-size:22px!important}.status{font-size:11px;margin-top:5px}.working{color:var(--amber)}
details.main{border-top:1px solid var(--line)}details.main>summary{cursor:pointer;padding:11px 14px;font-weight:700}.detail{padding:0 14px 16px}
.cols{display:grid;grid-template-columns:1fr 1fr;gap:10px}.box{border:1px solid var(--line);background:var(--soft);padding:11px}.box h3{margin:0 0 8px;font-size:15px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);margin-bottom:10px}.kpi{padding:9px;border-right:1px solid var(--line)}.kpi:last-child{border:0}.kpi b{display:block;font-size:17px}.kpi small{color:var(--muted)}
.comp{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.comp>div{border:1px solid var(--line);background:#fff;padding:9px}.comp b{font-size:20px;display:block}.comp small{display:block;color:var(--muted)}
.req{margin:0;padding-left:18px}.req li{margin:4px 0}.objects{margin-top:10px}.group{border:1px solid var(--line);margin:7px 0;background:#fff}.group summary{cursor:pointer;padding:8px 10px;font-weight:650}.tablewrap{overflow:auto;border-top:1px solid var(--line)}table{border-collapse:collapse;width:100%;font-size:12px}th,td{padding:7px 8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{background:var(--soft);position:sticky;top:0}.num{text-align:right;white-space:nowrap}
.warn{border-left:4px solid var(--amber)}.bad{border-left:4px solid var(--red)}.ok{border-left:4px solid #555}
.method{margin-top:12px;border:1px solid var(--line);padding:10px;background:#fff}.method summary{cursor:pointer;font-weight:650}
@media(max-width:1100px){.cardtop{grid-template-columns:64px 180px 1fr}.metrics{grid-column:1/-1;border-top:1px solid var(--line)}.identity{border-right:0}.cols{grid-template-columns:1fr}.comp{grid-template-columns:1fr 1fr}}
@media(max-width:680px){.content,.head{padding:12px}.brand{padding:14px 12px 0}.cardtop{grid-template-columns:58px 1fr}.map{grid-row:2;grid-column:1/-1;height:190px;border-top:1px solid var(--line);border-right:0}.identity{grid-column:2}.metrics{grid-template-columns:1fr 1fr}.metric:nth-child(4n){border-right:1px solid var(--line)}.metric:nth-child(2n){border-right:0}.comp{grid-template-columns:1fr}.kpis{grid-template-columns:1fr 1fr}.tools input{min-width:100%}}
</style></head><body><div class="shell"><div class="brand">DevelopAid<div class="bar"></div></div><header class="head"><div><h1>12 площадок КРТ · инвестиционный отбор</h1><div class="muted">Карта, обязательства, кадастровый состав и рейтинг 4×100</div></div><div class="muted">TEST · main не изменён</div></header><main class="content">
<div class="note"><b>Баллы не берутся из PDF.</b> PDF задаёт только список 12 лотов. Цена, поглощение, LLCR и нагрузка считаются DevelopAid; кадастровый состав проверяется пространственно по контуру КРТ.</div>
<div class="tools"><input id="q" placeholder="Лот или адрес"><select id="filter"><option value="">Все</option><option value="scored">Есть полный рейтинг</option><option value="building">Расчёт собирается</option></select><select id="sort"><option value="interest">По инвестиционному рейтингу</option><option value="llcr">По LLCR</option><option value="price">По цене рынка</option><option value="lot">По номеру лота</option></select><button class="primary" id="refresh">Пересчитать 12 площадок</button><span id="state" class="muted"></span></div>
<section id="cards" class="cards"><div class="note">Загружаю расчёты…</div></section>
</main></div><script>
const $=id=>document.getElementById(id),num=v=>v===null||v===undefined||v===''?null:Number(v),fmt=(v,d=0)=>num(v)===null?'—':Number(v).toLocaleString('ru-RU',{maximumFractionDigits:d}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],detailCache={},poll=null;
function scoreText(x){return x.score==null?'—':fmt(x.score)+'/100'}
function component(x,k){let c=(x.components||{})[k]||{};return c.score==null?'—':fmt(c.score,1)}
function card(x,i){let work=x.working?'<div class="status working">расчёт выполняется…</div>':'<div class="status">'+(x.score==null?'покрытие '+fmt(x.coverage_pct)+'%':'полный расчёт')+'</div>';
return '<article class="card" data-lot="'+x.lot+'"><div class="cardtop"><div class="rank"><span>место</span><b>'+(i+1)+'</b><span>лот '+x.lot+'</span></div><div class="map" id="map-'+x.lot+'"><div class="mapmsg">Карта загружается…</div></div><div class="identity"><span class="lotbadge">'+esc(x.okrug||'КРТ')+'</span><h2>'+esc(x.name)+'</h2><div class="muted">Лот '+x.lot+'</div><div class="slug">'+esc(x.slug||x.reason||'сопоставление с каталогом…')+'</div>'+work+'</div><div class="metrics">'+
 [['Инвест. рейтинг',scoreText(x),'score100'],['LLCR',x.llcr==null?'—':fmt(x.llcr,3)+'x',''],['Цена рынка',x.price_rub_sqm==null?'—':fmt(x.price_rub_sqm)+' ₽/м²',''],['Поглощение',x.local_area_per_month==null?'—':fmt(x.local_area_per_month,1)+' м²/мес.',''],['LLCR /100',component(x,'llcr'),''],['Цена /100',component(x,'price'),''],['Поглощение /100',component(x,'absorption'),''],['Нагрузка /100',component(x,'burden'),''],['Кадастровый выкуп',x.cadastral_buyout_mln==null?'—':fmt(x.cadastral_buyout_mln,1)+' млн ₽',''],['Нагрузка / CAPEX',x.burden_pct==null?'—':fmt(x.burden_pct,1)+'%',''],['ОКС в контуре',fmt((x.spatial_counts||{}).objects),''],['Покрытие',fmt(x.coverage_pct)+'%','']].map(a=>'<div class="metric"><b class="'+a[2]+'">'+a[1]+'</b><small>'+a[0]+'</small></div>').join('')+'</div></div><details class="main" ontoggle="if(this.open)loadDetail('+x.lot+')"><summary>Открыть карточку: что дают / что требуют / объекты / расчёт</summary><div class="detail" id="detail-'+x.lot+'"><div class="note">Загружаю карточку…</div></div></details></article>'}
function sorted(v){let s=$('sort').value;return [...v].sort((a,b)=>{if(s==='lot')return a.lot-b.lot;if(s==='llcr')return (b.llcr??-1)-(a.llcr??-1);if(s==='price')return (b.price_rub_sqm??-1)-(a.price_rub_sqm??-1);return (b.score!=null)-(a.score!=null)||(b.score??-1)-(a.score??-1)||(b.coverage_pct??0)-(a.coverage_pct??0)||(b.llcr??-1)-(a.llcr??-1)})}
function render(){let q=$('q').value.trim().toLowerCase(),f=$('filter').value,v=rows.filter(x=>(!q||[x.lot,x.name,x.okrug,x.slug].join(' ').toLowerCase().includes(q))&&(!f||(f==='scored'?x.score!=null:x.working||x.score==null)));v=sorted(v);$('cards').innerHTML=v.map(card).join('')||'<div class="note">Ничего не найдено.</div>';v.forEach(x=>{if(detailCache[x.lot])drawDetail(x.lot,detailCache[x.lot]);else quickDetail(x.lot)});$('state').textContent='Полный рейтинг: '+v.filter(x=>x.score!=null).length+' · расчёт идёт: '+v.filter(x=>x.working).length}
async function load(force=false){let u='/krt-12-preview/data'+(force?'?refresh=true':'');let d=await fetch(u).then(r=>r.json());rows=d.rows||[];render();if(rows.some(x=>x.working)){clearTimeout(poll);poll=setTimeout(()=>load(false),7000)}}
async function quickDetail(lot){try{let d=await fetch('/krt-12-preview/lot/'+lot).then(r=>r.json());if(d&&Object.keys(d).length){detailCache[lot]=d;drawMap(lot,d.map||{});let el=$('detail-'+lot);if(el&&el.closest('details').open)drawDetail(lot,d)}}catch(e){}}
async function loadDetail(lot){let el=$('detail-'+lot);if(detailCache[lot]){drawDetail(lot,detailCache[lot]);return}try{let d=await fetch('/krt-12-preview/lot/'+lot).then(r=>r.json());detailCache[lot]=d;drawDetail(lot,d);drawMap(lot,d.map||{})}catch(e){el.innerHTML='<div class="note bad">'+esc(e.message)+'</div>'}}
function drawMap(lot,m){let box=$('map-'+lot),rings=m.rings_merc||[],objs=m.objects||[],pts=rings.flat().filter(p=>Array.isArray(p)&&p.length>1);if(!pts.length){box.innerHTML='<div class="mapmsg">Контур КРТ ещё не получен</div>';return}let xs=pts.map(p=>+p[0]),ys=pts.map(p=>+p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),pad=Math.max(maxx-minx,maxy-miny)*.12||100,ax=minx-pad,bx=maxx+pad,ay=miny-pad,by=maxy+pad,w=700,h=430,px=x=>(x-ax)/(bx-ax)*w,py=y=>h-(y-ay)/(by-ay)*h,path=rr=>rr.map(r=>'M'+r.map(p=>px(+p[0]).toFixed(1)+' '+py(+p[1]).toFixed(1)).join('L')+'Z').join(' ');let src='/land/basemap?'+new URLSearchParams({bbox:[ax,ay,bx,by].join(','),width:String(w)}),op=objs.filter(o=>(o.rings_merc||[]).length).slice(0,180).map(o=>{let f=String(o.fate||'').toLowerCase(),stroke=f.includes('demolition')||f.includes('снос')?'#9c2929':f.includes('recon')||f.includes('рекон')?'#8a5d11':'#555';return '<path d="'+path(o.rings_merc)+'" fill="none" stroke="'+stroke+'" stroke-width="1.4"></path>'}).join('');box.innerHTML='<img src="'+src+'" alt=""><svg viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none">'+op+'<path d="'+path(rings)+'" fill="rgba(0,0,0,.04)" stroke="#111" stroke-width="4" stroke-dasharray="10 6"></path></svg><div class="mapmsg">контур КРТ · найдено ОКС '+fmt(objs.length)+'</div>'}
function val(v,unit=''){return v==null?'—':fmt(v)+(unit||'')}
function rowsTable(items){if(!items||!items.length)return '<div class="muted">Нет объектов в текущем наборе.</div>';return '<div class="tablewrap"><table><thead><tr><th>КН</th><th>Объект / адрес</th><th>Площадь</th><th>Кадастровая стоимость</th><th>Собственник</th></tr></thead><tbody>'+items.slice(0,120).map(o=>'<tr><td>'+esc(o.cadastral_number||'—')+'</td><td>'+esc(o.name||o.purpose||o.address||o.action_label||'—')+'</td><td class="num">'+(o.area_sqm==null?'—':fmt(o.area_sqm)+' м²')+'</td><td class="num">'+(o.cadastral_value_rub==null?'—':fmt(o.cadastral_value_rub)+' ₽')+'</td><td>'+esc(((o.owner||{}).name)||((o.owner||{}).group)||'не определён')+'</td></tr>').join('')+'</tbody></table></div>'}
function group(title,key,o,open=false){let a=(o||{})[key]||[];return '<details class="group" '+(open?'open':'')+'><summary>'+title+' — '+a.length+'</summary>'+rowsTable(a)+'</details>'}
function drawDetail(lot,d){let el=$('detail-'+lot);if(!el)return;if(!d||!d.available){el.innerHTML='<div class="note bad">'+esc((d||{}).reason||'Расчёт пока не готов')+'</div>';return}let p=d.programme||{},r=d.rating||{},C=r.components||{},cad=d.cadastre||{},b=d.burden||{},fin=d.finance||{},req=p.construction||[],social=p.social||[],unpriced=b.unpriced||[];let comps=['llcr','price','absorption','burden'].map(k=>{let x=C[k]||{};return '<div><b>'+(x.score==null?'—':fmt(x.score,1))+'</b><small>'+esc(x.name||k)+'</small><small>'+esc(x.score==null?(x.missing_reason||'нет данных'):(x.formula||''))+'</small></div>'}).join('');
let requirements=(req.length?'<ul class="req">'+req.map(x=>'<li>'+esc(typeof x==='string'?x:(x.label||x.name||JSON.stringify(x)))+'</li>').join('')+'</ul>':'<div class="muted">Текст обязательств из решения не получен.</div>')+(social.length?'<p><b>Социальные объекты:</b></p><ul class="req">'+social.map(x=>'<li>'+esc((x.label||x.kind||'объект')+(x.places?' · '+x.places+' мест':'')+(x.gba_sqm?' · '+fmt(x.gba_sqm)+' м²':''))+'</li>').join('')+'</ul>':'');
el.innerHTML='<div class="kpis">'+[['ГНС',val(p.total_gfa_sqm,' м²')],['Жильё',val(p.housing_gfa_sqm,' м²')],['Нежилое',val(p.nonresidential_gfa_sqm,' м²')],['Площадь КРТ',p.area_ha==null?'—':fmt(p.area_ha,2)+' га']].map(x=>'<div class="kpi"><b>'+x[1]+'</b><small>'+x[0]+'</small></div>').join('')+'</div>'+
'<div class="cols"><div class="box"><h3>Что даёт площадка</h3><p>Жильё: <b>'+val(p.housing_gfa_sqm,' м²')+'</b><br>Общественно-деловое: <b>'+val(p.business_gfa_sqm,' м²')+'</b><br>Прочее нежилое: <b>'+val(p.nonresidential_gfa_sqm,' м²')+'</b></p></div><div class="box"><h3>Что требует город</h3>'+requirements+(unpriced.length?'<div class="note warn"><b>Пока не монетизировано:</b><br>'+unpriced.map(esc).join('<br>')+'</div>':'')+'</div></div>'+
'<div class="box" style="margin-top:10px"><h3>Наш рейтинг 4×100</h3><div class="comp">'+comps+'</div><p><b>Итог:</b> '+(r.display_score==null?'—':fmt(r.display_score)+'/100')+' · покрытие '+fmt(r.coverage_pct)+'%</p>'+(r.arithmetic?'<p>'+esc(r.arithmetic)+'</p>':'')+'<p class="muted">'+esc(r.reason||'')+'</p></div>'+
'<div class="cols" style="margin-top:10px"><div class="box"><h3>Кадастровый контур</h3><p>Частный/не-Москва выкуп: <b>'+fmt((cad.private_buyout_rub||0)/1e6,1)+' млн ₽</b><br>из них земля: '+fmt((cad.private_land_rub||0)/1e6,1)+' млн ₽ · ОКС: '+fmt((cad.private_ocs_rub||0)/1e6,1)+' млн ₽<br>Москва исключена: '+fmt((cad.moscow_excluded_rub||0)/1e6,1)+' млн ₽<br>Иная публичная: '+fmt((cad.other_public_rub||0)/1e6,1)+' млн ₽<br>Неизвестна стоимость: '+fmt(cad.unknown_value_count)+' · неизвестен собственник: '+fmt(cad.unknown_owner_count)+'</p><p class="muted">Пространственный поиск: '+(cad.spatial_complete?'полный':'неполный')+(cad.spatial_problem?' · '+esc(cad.spatial_problem):'')+'</p></div><div class="box"><h3>Финансовая модель</h3><p>LLCR по известной нагрузке: <b>'+(fin.project_llcr_x==null?'—':fmt(fin.project_llcr_x,3)+'x')+'</b><br>Ordinary CAPEX: <b>'+(d.ordinary_capex_mln==null?'—':fmt(d.ordinary_capex_mln,1)+' млн ₽')+'</b><br>Нагрузка / CAPEX: <b>'+(b.burden_pct==null?'—':fmt(b.burden_pct,2)+'%')+'</b><br>Макс. цена права КРТ при LLCR 1,20: <b>'+(fin.max_krt_right_price_mln==null?'—':fmt(fin.max_krt_right_price_mln,1)+' млн ₽')+'</b></p></div></div>'+
'<div class="objects"><h3>Объекты внутри контура</h3>'+group('Под снос','demolition',d.objects,true)+group('Снос или реконструкция','demolition_or_reconstruction',d.objects)+group('Реконструкция','reconstruction',d.objects)+group('Сохранение','preservation',d.objects)+group('Кадастровый выкуп','buyout',d.objects,true)+group('Собственник не определён','unknown_owner',d.objects)+'</div>'+
'<details class="method"><summary>Методика</summary><p>Итог = (LLCR + цена рынка + поглощение + нагрузка КРТ) / 4. Каждый блок 0–100. Если один блок не подтверждён, общий балл не выводится и известные блоки не перенормируются. Поглощение — только м²/мес. Кадастровый выкуп: частные ЗУ и ОКС по кадастровой стоимости; Москва = 0; иная публичная собственность отдельно; неизвестное не превращается в ноль.</p></details>';drawMap(lot,d.map||{})}
$('q').addEventListener('input',render);$('filter').addEventListener('change',render);$('sort').addEventListener('change',render);$('refresh').onclick=()=>{detailCache={};load(true)};load(false);
</script></body></html>'''


def install(app, core=None):
    @app.get("/krt-12-preview/data", include_in_schema=False)
    async def krt_12_preview_data(refresh: bool = Query(default=False)):
        if core is None:
            return JSONResponse({"rows":[],"error":"authoritative core unavailable"}, status_code=503)
        rows = krt_12_analysis.summaries(core, force=bool(refresh))
        return JSONResponse({"rows":rows,"method":"issue #485 · own calculations, PDF only selects lots"},
                            headers={"Cache-Control":"no-store"})

    @app.get("/krt-12-preview/lot/{lot}", include_in_schema=False)
    async def krt_12_preview_lot(lot: int, refresh: bool = Query(default=False)):
        if core is None:
            return JSONResponse({"error":"authoritative core unavailable"}, status_code=503)
        definition = next((x for x in krt_12_analysis.LOT_DEFS if int(x["lot"]) == int(lot)), None)
        if not definition:
            return JSONResponse({"error":"unknown lot"}, status_code=404)
        if refresh:
            krt_12_analysis.refresh(definition, core, force=True)
        cached = krt_12_analysis.load(lot)
        if not cached or (cached.get("stale") and not cached.get("working")):
            krt_12_analysis.refresh(definition, core)
            cached = krt_12_analysis.load(lot)
        return JSONResponse(cached, headers={"Cache-Control":"no-store"})

    @app.get("/krt-12-preview", response_class=HTMLResponse, include_in_schema=False)
    async def krt_12_preview():
        return HTMLResponse(PAGE, headers={"Cache-Control":"no-store, must-revalidate"})
