"""Presentation patch for the DevelopAid PDF first page.

Uses the existing server-side OSM basemap renderer and the factual EGRN contour.
Also replaces the sixth KPI card with total project expenses.
Financial calculations are not changed.
"""

from __future__ import annotations

import io
from typing import Any

import pdf_first_page_extension as base


def _number(value: Any) -> float:
    try:
        result = float(value or 0)
    except (TypeError, ValueError):
        return 0.0
    return result if result == result else 0.0


def _total_expenses(result: dict[str, Any]) -> float:
    report = result.get("report") or {}
    rows = report.get("expense_structure") or []
    total = sum(
        _number(row.get("value"))
        for row in rows
        if isinstance(row, dict)
    )
    if total > 0:
        return total
    summary = result.get("summary") or {}
    for key in ("total_expenses", "expenses_total", "total_costs", "total_cost"):
        value = _number(summary.get(key))
        if value > 0:
            return value
    return 0.0


def _parcel_geometry(payload: dict[str, Any]):
    items = base._parcel_items(payload)
    rings = [
        ring for item in items for ring in (item.get("contour_merc") or [])
        if isinstance(ring, list) and len(ring) >= 3
    ]
    points = [
        point for ring in rings for point in ring
        if isinstance(point, (list, tuple)) and len(point) >= 2
    ]
    return items, rings, points


def _map_bbox(points: list[Any], target_aspect: float) -> tuple[float, float, float, float] | None:
    """BBox with visible context and the same aspect ratio as the PDF slot."""
    if not points:
        return None
    xs = [_number(point[0]) for point in points]
    ys = [_number(point[1]) for point in points]
    min_x, max_x, min_y, max_y = min(xs), max(xs), min(ys), max(ys)
    span_x, span_y = max_x - min_x, max_y - min_y
    if not (span_x > 0 and span_y > 0):
        return None

    # Give the parcel enough surrounding streets/buildings to orient the reader.
    # A minimum 250 m on each side matches the map shown in the web interface.
    context_x = max(span_x * 0.22, 250.0)
    context_y = max(span_y * 0.22, 250.0)
    min_x -= context_x
    max_x += context_x
    min_y -= context_y
    max_y += context_y

    span_x, span_y = max_x - min_x, max_y - min_y
    current_aspect = span_x / span_y
    if current_aspect < target_aspect:
        wanted_x = span_y * target_aspect
        extra = (wanted_x - span_x) / 2.0
        min_x -= extra
        max_x += extra
    elif current_aspect > target_aspect:
        wanted_y = span_x / target_aspect
        extra = (wanted_y - span_y) / 2.0
        min_y -= extra
        max_y += extra
    return min_x, min_y, max_x, max_y


def _osm_parcel_image(payload: dict[str, Any], core: Any, width: float = 260,
                      height: float = 126):
    """Real OSM basemap with every stored EGRN contour overlaid.

    The map is generated by the existing ``core.land_basemap`` implementation,
    i.e. the same server-side OSM renderer used by DevelopAid itself. If OSM is
    temporarily unavailable, PDF generation falls back to the old schematic.
    """
    from reportlab.platypus import Image as RLImage

    _items, rings, points = _parcel_geometry(payload)
    bbox = _map_bbox(points, width / height)
    if bbox is None:
        return None

    try:
        response = core.land_basemap(
            bbox=",".join(f"{value:.3f}" for value in bbox),
            width=960,
        )
        raw = getattr(response, "body", None)
        if not raw:
            raise RuntimeError("land_basemap returned no image bytes")

        from PIL import Image as PILImage, ImageDraw, ImageFont

        image = PILImage.open(io.BytesIO(raw)).convert("RGBA")
        px_w, px_h = image.size
        if px_w < 64 or px_h < 32:
            raise RuntimeError(f"land_basemap returned implausible size {px_w}x{px_h}")
        draw = ImageDraw.Draw(image, "RGBA")
        bx0, by0, bx1, by1 = bbox

        def project(point):
            x, y = _number(point[0]), _number(point[1])
            return (
                (x - bx0) / (bx1 - bx0) * px_w,
                (by1 - y) / (by1 - by0) * px_h,
            )

        stroke = max(4, round(px_w / 240))
        for ring in rings:
            projected = [project(point) for point in ring]
            if projected and projected[0] != projected[-1]:
                projected.append(projected[0])
            if len(projected) >= 4:
                # A white halo keeps the cadastral line readable over dense OSM.
                draw.line(projected, fill=(255, 255, 255, 240), width=stroke + 4,
                          joint="curve")
                draw.line(projected, fill=(20, 20, 20, 255), width=stroke,
                          joint="curve")

        # Attribution is part of the static export. Attribution failure must not
        # discard an otherwise valid map.
        try:
            label = "© OpenStreetMap"
            font = ImageFont.load_default()
            box = draw.textbbox((0, 0), label, font=font)
            tw, th = box[2] - box[0], box[3] - box[1]
            x, y = 9, px_h - th - 9
            draw.rounded_rectangle((x - 4, y - 3, x + tw + 4, y + th + 3),
                                   radius=3, fill=(255, 255, 255, 225))
            draw.text((x, y), label, fill=(40, 40, 40, 255), font=font)
        except Exception:
            pass

        out = io.BytesIO()
        image.convert("RGB").save(out, format="JPEG", quality=90)
        out.seek(0)

        # Platypus Image accepts the file-like object itself. Passing ImageReader
        # here caused the previous implementation to throw and silently take the
        # schematic fallback on every report.
        flowable = RLImage(out, width=width, height=height)
        flowable._developaid_image_buffer = out
        return flowable
    except Exception:
        return _ORIGINAL_PARCEL_DRAWING(payload, core, width=width, height=height)


def _patched_front_page_flowables(payload: dict[str, Any], core: Any):
    flowables = _ORIGINAL_FRONT_PAGE(payload, core)
    try:
        result = payload.get("result") or {}
        total = _total_expenses(result)
        if total <= 0 or not flowables:
            return flowables

        # Existing structure: KeepTogether -> blocks -> KPI Table -> six cell Tables.
        keep = flowables[0]
        blocks = getattr(keep, "_content", None) or []
        card_table = blocks[2]
        cell = card_table._cellvalues[1][2]
        label_para = cell._cellvalues[0][0]
        value_para = cell._cellvalues[1][0]

        from reportlab.platypus import Paragraph

        cell._cellvalues[0][0] = Paragraph("Расходы всего", label_para.style)
        cell._cellvalues[1][0] = Paragraph(core._pdf_money(total), value_para.style)
    except Exception:
        # The summary is presentation-only; never make the PDF fail because of it.
        pass
    return flowables


_ORIGINAL_PARCEL_DRAWING = base._parcel_drawing
_ORIGINAL_FRONT_PAGE = base._front_page_flowables


def install(core: Any) -> None:
    base._parcel_drawing = _osm_parcel_image
    base._front_page_flowables = _patched_front_page_flowables
    base.install(core)
